export const ActionTypes = {
    SET_PRODUCTS : "SET_PRODUCTS",
    SELECTED_PRODUCT : "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT : "REMOVE_SELECTED_PRODUCT",
    ADD_PRODUCT : "ADD_PRODUCT",
    DELETE_PRODUCT : "DELETE_PRODUCT",
    GET_SINGLE_PRODUCT : "GET_SINGLE_PRODUCT",
};